import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/custom/theme-provider";
import  DeskNavbar  from "@/components/custom/desk-navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const mono = localFont({
  src: [
    {
      path: '../../public/fonts/caros.otf',
      weight: "400",
    },
    {
      path: '../../public/fonts/caros-light.otf',
      weight: "300",
    },
    {
      path: '../../public/fonts/caros-bold.otf',
      weight: "700",
    },
    {
      path: '../../public/fonts/caros-black.otf',
      weight: "900",
    },

  ],
  variable: '--font-mono',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${mono.variable} ${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DeskNavbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}